# Generated by Django 3.1.6 on 2021-02-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rfid',
            field=models.IntegerField(default=0, help_text='ID RFID метки'),
        ),
    ]
